[package]
name = "mtaalink"
version = "0.1.0"
edition = "2024"


[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "macros"] }
askama = "0.12"
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"
axum-server = "0.6"