// Curated list of common Kenyan service areas, shown as suggestions in the
// location combobox used during onboarding and search. Stored as plain
// "Area, County" text so it stays compatible with the existing ILIKE-based
// location search and filtering.
export const KENYA_LOCATIONS: string[] = [
  // Nairobi
  "Westlands, Nairobi",
  "Parklands, Nairobi",
  "Lavington, Nairobi",
  "Kilimani, Nairobi",
  "Kileleshwa, Nairobi",
  "Karen, Nairobi",
  "Langata, Nairobi",
  "South B, Nairobi",
  "South C, Nairobi",
  "Nairobi West, Nairobi",
  "CBD, Nairobi",
  "Ngara, Nairobi",
  "Eastleigh, Nairobi",
  "Pangani, Nairobi",
  "Kawangware, Nairobi",
  "Dagoretti, Nairobi",
  "Embakasi, Nairobi",
  "Donholm, Nairobi",
  "Buruburu, Nairobi",
  "Umoja, Nairobi",
  "Komarock, Nairobi",
  "Kayole, Nairobi",
  "Pipeline, Nairobi",
  "Kasarani, Nairobi",
  "Roysambu, Nairobi",
  "Githurai, Nairobi",
  "Kahawa, Nairobi",
  "Zimmerman, Nairobi",
  "Ruaka, Nairobi",
  "Ngong Road, Nairobi",
  "Industrial Area, Nairobi",

  // Greater Nairobi / satellite towns
  "Ngong, Kajiado",
  "Rongai, Kajiado",
  "Kitengela, Kajiado",
  "Kiambu Town, Kiambu",
  "Kikuyu, Kiambu",
  "Ruiru, Kiambu",
  "Thika, Kiambu",
  "Limuru, Kiambu",
  "Athi River, Machakos",
  "Mlolongo, Machakos",
  "Machakos Town, Machakos",

  // Mombasa
  "Nyali, Mombasa",
  "Bamburi, Mombasa",
  "Kisauni, Mombasa",
  "Likoni, Mombasa",
  "Changamwe, Mombasa",
  "Mombasa Island, Mombasa",

  // Other major towns
  "Kisumu Central, Kisumu",
  "Milimani, Kisumu",
  "Nakuru Town, Nakuru",
  "Naivasha, Nakuru",
  "Eldoret, Uasin Gishu",
  "Kitale, Trans Nzoia",
  "Kakamega Town, Kakamega",
  "Kericho Town, Kericho",
  "Nyeri Town, Nyeri",
  "Nanyuki, Laikipia",
  "Meru Town, Meru",
  "Embu Town, Embu",
  "Garissa Town, Garissa",
  "Malindi, Kilifi",
];
